on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build and deploy
        run: |
          npm run build
          npm run deploy

      - name: Verify deployment
        uses: actions/verify-deployment@v1
        with:
          url: C:\Users\saikuhe\Desktop\welcome page\index.html
